
// import 'public/vendor/bootstrap/css/bootstrap.min.css'

import 'public/vendor/font-awesome/css/all.min.css'
import 'public/vendor/currency-flags/css/currency-flags.min.css'
import 'public/vendor/bootstrap-select/css/bootstrap-select.min.css'

import 'public/vendor/owl.carousel/assets/owl.carousel.min.css'
import 'public/css/stylesheet.css'
import type { Metadata } from 'next'


// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">

      <body  >

        <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" />
        <link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css" />

        <link rel="stylesheet" type="text/css" href="vendor/font-awesome/css/all.min.css" />
        {/* <link rel="stylesheet" type="text/css" href="vendor/bootstrap-select/css/bootstrap-select.min.css" /> */}
        <link rel="stylesheet" type="text/css" href="vendor/currency-flags/css/currency-flags.min.css" />
        {/* <link rel="stylesheet" type="text/css" href="vendor/owl.carousel/assets/owl.carousel.min.css" /> */}
        <link rel="stylesheet" type="text/css" href="css/stylesheet.css" />

        {/* <link id="color-switcher" type="text/css" rel="stylesheet" href="#" /> */}

        {/* <div id="preloader">
          <div data-loader="dual-ring"></div>
        </div> */}
        {children}
        {/* <a id="back-to-top" data-bs-toggle="tooltip" title="Back to Top" href="javascript:void(0)"><i
          className="fa fa-chevron-up"></i></a> */}


        <div className="modal fade" id="videoModal" tabIndex={-1} role="dialog">
          <div className="modal-dialog modal-lg modal-dialog-centered" role="document">
            <div className="modal-content bg-transparent border-0">
              <button type="button" className="btn-close btn-close-white ms-auto me-n3" data-bs-dismiss="modal"
                aria-label="Close"></button>
              <div className="modal-body p-0">
                <div className="ratio ratio-16x9">
                  <iframe id="video" src="" allow="autoplay;" allowFullScreen></iframe>
                </div>
              </div>
            </div>
          </div>
        </div>


        <script src="vendor/jquery/jquery.min.js"></script>
        <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="vendor/bootstrap-select/js/bootstrap-select.min.js"></script>

        <script src="vendor/owl.carousel/owl.carousel.min.js"></script>
        <script src="js/switcher.min.js"></script>
        <script src="js/theme.js"></script>
      </body>
    </html>
  )
}
